version: '3'
services:
  redis-pandora:
    image: redis:latest
    container_name: redis-pandora
    env_file:
      - .env
    hostname: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
